# Generated by Django 3.0.4 on 2020-05-03 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='company',
        ),
    ]
